# Generated by Django 3.0.6 on 2020-05-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='portfolio/images')),
                ('description', models.CharField(max_length=2000)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
