# Generated by Django 3.0.6 on 2020-05-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200526_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='url',
        ),
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio/images'),
        ),
    ]
