# Generated by Django 3.0.6 on 2020-05-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='projects',
        ),
        migrations.DeleteModel(
            name='book',
        ),
        migrations.DeleteModel(
            name='learn',
        ),
        migrations.DeleteModel(
            name='people',
        ),
    ]
