# Generated by Django 3.0.6 on 2020-05-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20200529_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='articles',
            new_name='article',
        ),
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
        migrations.RenameModel(
            old_name='materials',
            new_name='material',
        ),
    ]
