# Generated by Django 3.0.6 on 2020-06-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='url',
            new_name='url_1',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image',
        ),
        migrations.RemoveField(
            model_name='people',
            name='title',
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='topic_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='people',
            name='topic_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='people',
            name='topic_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='people',
            name='url_2',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
