# Generated by Django 3.0.6 on 2020-06-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20200602_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='title',
        ),
    ]
