# Generated by Django 3.0.6 on 2020-06-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
