# Generated by Django 3.0.6 on 2020-06-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_auto_20200610_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('topic_1', models.CharField(blank=True, max_length=1000)),
                ('topic_2', models.CharField(blank=True, max_length=1000)),
                ('topic_3', models.CharField(blank=True, max_length=1000)),
                ('url_1', models.URLField(blank=True)),
            ],
        ),
    ]
