# Generated by Django 3.0.6 on 2020-05-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
