# Generated by Django 3.0.6 on 2020-06-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
